### PR TITLE
virt-test: Add RSS IPv6 version

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID: 798898, 1181985

**Comment by PyLearner** [comment]
Acked-by: Meng Yang meyang@redhat.com

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by ypu** [comment]
Thanks @xutian @PyLearner and @suqinhuang will merge it.

**Pull request merged**
