### PR TITLE
virt-test: guest-os: Add RHEL.6.7 guest os config.

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1251372

### CODE REVIEW

**Comment by spcui** [comment]
Hi @CongSmile 
please also update host-kernel in tp-qemu too.

**Comment by CongSmile** [comment]
Hi @spcui 

Thanks.

I have created the PR #tp-qemu/pull/438 .
Could you help review it again?

**Comment by spcui** [comment]
Acked-by: scui@redhat.com

**Comment by xutian** [comment]
Merged. thanks @CongSmile  and @spcui

**Pull request merged**
