### PR TITLE
virttest.iscsi: Ignore status for iscsiadm.

### PR DESCRIPTION
**Pull request by rbian**
Get rid of exception if iscsiadm command fails to excute
during iscsi cleanup process.

### CODE REVIEW

**Comment by waynesun09** [comment]
ACK

**Comment by yumingfei** [comment]
Looks fine to me. But please remove the merging information because it's useless for autotest.

**Comment by rbian** [comment]
@yumingfei , done.

**Comment by yumingfei** [comment]
Thanks @waynesun09, @rbian

**Pull request merged**
