### PR TITLE
utils_test.libvirt: Add a function to update polkit rule

### PR DESCRIPTION
**Pull request by will-Do**
Signed-off-by: Yanbing Du <ydu@redhat.com>

### CODE REVIEW

**Comment by waynesun09** [comment]
@will-Do could you use function ```file_replace_append``` in ```LibvirtPolkitConfig``` ?

**Comment by will-Do** [comment]
Yes, I saw that function, and since it can only update content in one line and a new file(rename) used during update, so I rewrite the update step which just use ```re.sub```

**Comment by will-Do** [comment]
Maybe I can rewrite that function then reuse it

**Comment by waynesun09** [comment]
@will-Do no need to update that function, it only used by the _setup_libvirtd function, which could be replaced by utils_config.LibvirtdConfig().
So, ACK for this.

**Pull request merged**
