### PR TITLE
utils_misc: Add fuction get node cpu topology info

### PR DESCRIPTION
**Pull request by waynesun09**
Add new get cpu topology dict function, retrieve the cpu topology
info in certain node from sysfs.

Also fix get node cpus problem, the findall regex need match to
the end of line, and set extra_cpus from node 0 when current cpus
node not as 0.

Signed-off-by: Wayne Sun <gsun@redhat.com>

### CODE REVIEW

**Comment by will-Do** [comment]
There's a method ```get_cpu_info``` in virttest/utils_misc.py, which contains the cpu topology info, I guess you can use it directly.

**Comment by waynesun09** [comment]
@will-Do The get_cpu_topology in NumaNode is for get the detail cpu info with soket_id, core_id, siblings of certain cell in current NumaNode instance.
The get_cpu_info use 'lscpu' command to get basic host cpu info, they are not the same.

**Comment by will-Do** [comment]
Yes, it's different.
ACK this PR

**Comment by waynesun09** [comment]
@will-Do thx, merging now.

**Pull request merged**
