### PR TITLE
virt: Run type script in a sequence defined by type parameter.

### PR DESCRIPTION
**Pull request by FengYang**
ID: 1010789
Signed-off-by: Feng Yang <fyang@redhat.com>

### CODE REVIEW

**Comment by ypu** [comment]
@FengYang Hi should we also update the run_once in standalone_test.py?

**Comment by FengYang** [comment]
On 01/08/2015 06:51 PM, Yiqiao Pu wrote:
>
> @FengYang <https://github.com/FengYang> Hi should we also update the
> run_once in standalone_test.py?
>
Maybe, will check it. Just never use it

**Comment by FengYang** [comment]
Update it.

**Comment by Hao-Liu** [comment]
@FengYang, Just a little curious. What's the difference after this change? Shouldn't the result be the same?

**Comment by FengYang** [comment]
On 01/20/2015 03:00 PM, Hao Liu wrote:
>
> @FengYang <https://github.com/FengYang>, Just a little curious. What's 
> the difference after this change? Shouldn't the result be the same?
>
In current code. If we set type = "boot shutdown". It may run shutdown 
first, but we may want to make sure boot run firstly.

**Comment by Hao-Liu** [comment]
Right, understood and Acked.

**Comment by ypu** [comment]
LGTM

Acked-by:Yiqiao Pu <ypu@redhat.com>

**Comment by ypu** [comment]
Thanks @FengYang and @Hao-Liu will merge it.

**Pull request merged**
