### PR TITLE
virt-test: Modify serial port parameter from isa_serials to serials

### PR DESCRIPTION
**Pull request by ypu**
As we support powerpc now the serials in power platform is spapr-vty
but not isa. So modify the parameter name to make the code can
work on different platform.

### CODE REVIEW

**Comment by ypu** [comment]
ID: 1220714

**Comment by Zhengtong** [comment]
acked

**Comment by ngu-niny** [comment]
Acked.
On ppc64le host, after download the upstream autotest/virt-test/tp-qemu code and 'git am' the patch, I have run some basic function test cases, i.e. unattended install, boot, reboot, system_powerdown, the test is passed without any the patch related problem. The software versions on the host/guest are:
Host kernel: 3.10.0-244.ael7b.ppc64le
Guest kernel: 3.10.0-229.el7.ppc64/3.10.0-229.ael7b.ppc64le
Qemu KVM: qemu-kvm-rhev-2.3.0-1.ael7b.ppc64le

**Comment by xutian** [comment]
LGTM,

Acked-by: Xu Tian <xutian@redhat.com>

**Comment by ypu** [comment]
Thanks @Zhengtong @ngu-niny and @xutian will merge it.

**Pull request merged**
