### PR TITLE
Add support for Ubuntu Server 14.04.1 (i386, x86_64)

### PR DESCRIPTION
**Pull request by igord-daynix**
Tested!

Signed-off-by: Igor Derzhavets <igor.derzhavets@ravellosystems.com>

### CODE REVIEW

**Comment by xutian** [comment]
LGTM,

Acked-by: @xutian

**Comment by yumingfei** [comment]
ACKed.

**Comment by yumingfei** [comment]
Thanks @igord-daynix

**Comment by igord-daynix** [comment]
Welcome @yumingfei

**Pull request merged**
