### PR TITLE
libvirt: Add basic support of ESX protocol

### PR DESCRIPTION
**Pull request by igord-daynix**
Tested with ESXi 5.5.

### CODE REVIEW

**Comment by lmr** [comment]
Hey @igord-daynix, pylint caught up a little mistake:

    $ inspekt lint
    ************* Module virt-test.run
    E0602:684,26: VirtTestApp._process_libvirt_specific_options: Undefined variable 'SUPPORTED_LIBVIRT_DRIVERS'
    Pylint check fail: /home/travis/build/autotest/virt-test/run
    Syntax check FAIL

Please fix it and re-send, thanks!

**Comment by igord-daynix** [comment]
FIXED!
I apologize for the inconvenience.
Thank you!

**Comment by will-Do** [comment]
LGTM

**Comment by waynesun09** [comment]
ACK and merging now.

**Pull request merged**
