### PR TITLE
virt-test: iscsi.py: emulated_image only for emulational_iscsi

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1242424

### CODE REVIEW

**Comment by PandaWei** [comment]
Is there any failure?

**Comment by CongSmile** [comment]
Hi @PandaWei 

Yes, it will failed when use iscsi instead of emulated_iscsi.

Traceback (most recent call last):
    File "/home/iscsi/staf-kvm-devel/autotest-devel/client/shared/test.py", line 823, in _call_test_function
      return func(*args, **dargs)
    File "/home/iscsi/staf-kvm-devel/autotest-devel/client/shared/test.py", line 291, in execute
      postprocess_profiled_run, args, dargs)
    File "/home/iscsi/staf-kvm-devel/autotest-devel/client/shared/test.py", line 209, in _call_run_once
      *args, **dargs)
    File "/home/iscsi/staf-kvm-devel/autotest-devel/client/shared/test.py", line 313, in run_once_profiling
      self.run_once(*args, **dargs)
    File "/home/iscsi/staf-kvm-devel/autotest-devel/client/tests/virt/virt.py", line 145, in run_once
      params = env_process.preprocess(self, params, env)
    File "/home/iscsi/staf-kvm-devel/autotest-devel/client/shared/error.py", line 141, in new_fn
      return fn(*args, **kwargs)
    File "/home/iscsi/staf-kvm-devel/autotest-devel/client/tests/virt/virttest/env_process.py", line 580, in preprocess
      iscsidev = qemu_storage.Iscsidev(params, base_dir, "iscsi")
    File "/home/iscsi/staf-kvm-devel/autotest-devel/client/tests/virt/virttest/qemu_storage.py", line 524, in __init__
      super(Iscsidev, self).__init__(params, root_dir, tag)
    File "/home/iscsi/staf-kvm-devel/autotest-devel/client/tests/virt/virttest/storage.py", line 515, in __init__
      self.iscsidevice = iscsi.Iscsi.create_iSCSI(params, root_dir=root_dir)
    File "/home/iscsi/staf-kvm-devel/autotest-devel/client/tests/virt/virttest/iscsi.py", line 761, in create_iSCSI
      iscsi_instance = IscsiLIO(params, root_dir)
    File "/home/iscsi/staf-kvm-devel/autotest-devel/client/tests/virt/virttest/iscsi.py", line 504, in __init__
      self.device = "device.%s" % os.path.basename(self.emulated_image)
  AttributeError: 'IscsiLIO' object has no attribute 'emulated_image'

**Comment by PandaWei** [comment]
OK, good catch.

But there's some advice.

Please move self.device = "device.%s" % os.path.basename(self.emulated_image) to the __init__ of _IscsiComm().
like below,

  # CHAP AUTHENTICATION
        self.chap_flag = False
        self.chap_user = params.get("chap_user")
        self.chap_passwd = params.get("chap_passwd")
        if self.chap_user and self.chap_passwd:
            self.chap_flag = True

        if params.get("emulated_image"):
            self.initiator = None
            emulated_image = params.get("emulated_image")
            self.emulated_image = os.path.join(root_dir, emulated_image)
            self.device = "device.%s" % os.path.basename(self.emulated_image)
             <-----------------cut--------------->
        else:
            self.device = None

**Comment by CongSmile** [comment]
Hi @PandaWei 

Yes, _IscsiComm() is a better place to judge the emulated_image.

Thanks for your help.

And I have updated the code, could you help review it again?

Thanks.

**Comment by PandaWei** [comment]
ACK, Good Enough.
I guess that all of failed cases pass now.
If you paste the latest result,
I think we can merge this PR.

**Comment by CongSmile** [comment]
For iscsi:
        (Result file: /home/staf-kvm-devel/autotest-devel/client/results/default/status)
virt.qemu.smp_2.2048m.repeat1.pre_test.Host_RHEL.7.2.iscsi.raw.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native    GOOD       2008     completed successfully

**Comment by PandaWei** [comment]
Thanks @CongSmile
Merge now.

**Pull request merged**
