### PR TITLE
Adding RHEL70 ppc64 guest os config and kickstart file

### PR DESCRIPTION
**Pull request by sathnaga**
Adding RHEL70 ppc64 guest os configuration file and kickstart file.

### CODE REVIEW

**Comment by yumingfei** [comment]
Acked.

**Comment by sathnaga** [comment]
@yumingfei , can you pls push it, Thanks in advance.

**Comment by yumingfei** [comment]
OK~Thanks :)

**Comment by ldoktor** [comment]
Well it's already merged, but what makes the RHEL7 ppc64 kickstart so different than i686 and x86_64 kickstart? It should work fine (actually it works fine, I'm already using it). Although might I ask you to review this: https://github.com/autotest/virt-test/pull/2012 it's also about PPC64 and it modifies the default config to support PPC64 out of the box.

**Comment by yumingfei** [comment]
@ldoktor , sorry, it confuses you. Since it already works, you can unify all platforms later or you can change it in your PR.
And @sathnaga , do you have any idea on @ldoktor's work?

**Comment by yumingfei** [comment]
@ldoktor , sorry, it confuses you. Since it already works, you can unify all platforms later or you can change it in your PR.
And @sathnaga , do you have any idea on @ldoktor's work?

**Comment by sathnaga** [comment]
@ldoktor @yumingfei : Sure, I like @ldoktor idea of having common code for all archs, will use his patch  and give more comments if any, Thanks :-)

**Comment by sathnaga** [comment]
closing as merged

**Pull request merged**
