### PR TITLE
virttest/libvirt_xml/pool_xml: revise pool_rename

### PR DESCRIPTION
**Pull request by PandaWei**
Main modification as following,
* Remove the call for pool_destroy().
  delete_pool() will destroy pool if it's active,
  so no need to call pool_destroy() explicitly.
* Call uniform cleanup function while failure appears.
* No catch CmdError for pool_xml.define_pool.
  because it will return True or False and
  keep consistence with others.

### CODE REVIEW

**Comment by will-Do** [comment]
ACK

**Comment by yangdongsheng** [comment]
Okey, please test it fully before pushing it in master.

**Comment by PandaWei** [comment]
Ok, I will push test result later.

**Comment by PandaWei** [comment]
Due to there's no cases call pool_rename() directly.
so I wrote a small case to test this function. as follow,
def run(test, params, env):
    """
    Test the virsh pool commands

    """

    old_pool = "default"
    new_pool = "new-pool"


    _pool = PoolXML()
    result = virsh.pool_list("--all", ignore_status=True)
    logging.info("rename before:%s" % result)
    # first
    _pool.pool_rename(old_pool, new_pool)

    result = virsh.pool_list("--all", ignore_status=True)
    logging.info("------first rename-------:\n%s" % result)

    # second
    _pool.pool_rename(new_pool, old_pool)

    result = virsh.pool_list("--all", ignore_status=True)
    logging.info("------second rename-----:\n%s" % result)

**Comment by PandaWei** [comment]
The result as following,
19:36:36 INFO | rename before:* Command: 
    /usr/bin/virsh pool-list --all
Exit status: 0
Duration: 0.0600039958954

stdout:
Name                 State      Autostart 
-----------------------------------------
default              active     no
19:36:36 INFO | Deleted pool 'default'
19:36:36 DEBUG| Rename pool: default to new-pool.
19:36:36 INFO | Started pool 'new-pool'
19:36:36 INFO | ------first rename-------:
* Command: 
    /usr/bin/virsh pool-list --all
Exit status: 0
Duration: 0.0535728931427

stdout:
Name                 State      Autostart 
-----------------------------------------
new-pool             active     no
19:36:37 INFO | Deleted pool 'new-pool'
19:36:37 DEBUG| Rename pool: new-pool to default.
19:36:37 INFO | Started pool 'default'
19:36:37 INFO | ------second rename-----:
* Command: 
    /usr/bin/virsh pool-list --all
Exit status: 0
Duration: 0.0511300563812

stdout:
Name                 State      Autostart 
-----------------------------------------
default              active     no

**Comment by PandaWei** [comment]
In fact, I debug it by pdb many times before pushing it.
You can rely on it

**Comment by waynesun09** [comment]
ACK and merging now, thx

**Pull request merged**
