### PR TITLE
Add a parameter to bootstrap.

### PR DESCRIPTION
**Pull request by rbian**
Modify bootstrap parameter for other script to use "force_update" to update config files in noninteractive mode.

### CODE REVIEW

**Comment by yumingfei** [comment]
But shouldn't you provide an option in script 'run'?

**Comment by rbian** [comment]
There is already an option "--update-config" in run. Thanks @yumingfei

**Comment by yumingfei** [comment]
I mean the place we call bootstrap(...) and this '--update-config' does not work for it.
```
line 871:
                download_image = False
                keep_image = False

            test_dir = data_dir.get_backend_dir(self.options.type)
            bootstrap.bootstrap(test_name=self.options.type, test_dir=test_dir,
                                base_dir=data_dir.get_data_dir(),
                                default_userspace_paths=default_userspace_paths,
                                check_modules=check_modules,
                                online_docs_url=online_docs_url,
                                interactive=interactive,
                                download_image=download_image,
                                selinux=self.options.selinux_setup,
                                restore_image=keep_image,
                                verbose=self.options.verbose,
                                update_providers=self.options.update_providers,
                                guest_os=(self.options.guest_os or
                                          self.option_parser.default_guest_os))
            sys.exit(0)
```

So the force_update will be always False for function bootstrap(...) as its default value.
Do I misunderstand?

**Comment by rbian** [comment]
You are right! I will update it.

**Comment by rbian** [comment]
@yumingfei ,
Look at the code again, "bootstrap" option in "run" should always be excuted in interactive mode, so no need to specify "force_update" in this function.
 841         if self.options.bootstrap:
...
 845             interactive = True

**Comment by will-Do** [comment]
Yes, it is, ack this patch

**Comment by waynesun09** [comment]
ACK

**Comment by Hao-Liu** [comment]
Merge this PR. Thanks @rbian, @yumingfei, @will-Do, @waynesun09

**Pull request merged**
