### PR TITLE
remove useless module imported

### PR DESCRIPTION
**Pull request by xutian**
ID: 1190967
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by spcui** [comment]
LGTM
Acked-by: @spcui

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by PandaWei** [comment]
ACK

**Comment by FengYang** [comment]
Thanks @xutian , @spcui @CongSmile and @PandaWei

**Pull request merged**
