### PR TITLE
Disable virtio_scsi under sles11.2 guests as it was not supported in the...

### PR DESCRIPTION
**Pull request by yaxue**
...se guests

Signed-off-by: Yang Xue <yaxue@redhat.com>

### CODE REVIEW

**Comment by yaxue** [comment]
1178603

https://www.suse.com/documentation/sles11/singlehtml/book_kvm/book_kvm.html#sec.kvm.requires.hardware

**Comment by FengYang** [comment]
Acked-by: FengYang

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by FengYang** [comment]
Thanks @yaxue @CongSmile

**Pull request merged**
