### PR TITLE
shared.cfg.guest-hw: Add virtio_rng driver in win_virtio_update

### PR DESCRIPTION
**Pull request by spcui**
This patch will install the virtio_rng driver in
win_virtio_update.install_driver testcase.

ID: 1192327

### CODE REVIEW

**Comment by xiagao** [comment]
Acked-by: Xiaoling Gao  <xiagao@redhat.com>

**Comment by xiagao** [comment]
NACK-by: Xiaoling Gao <xiagao@redhat.com>
need to do more research, so nack firstly.

**Comment by xiagao** [comment]
Acked-by: Xiaoling Gao <xiagao@redhat.com>

**Comment by spcui** [comment]
closed it, it's incorrect patch.

**Pull request closed without merging**
