### PR TITLE
virt-test: fix reboot issue on devel guest

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1205993

**Comment by PyLearner** [comment]
Works for me ,i run the case and it is ok.

**Comment by CongSmile** [comment]
Hi @xutian 

The code is fine for me, but I'm really curious about the timeout set.

Could you help explain it?

Thanks.

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by xutian** [comment]
thanks @CongSmile  and @PyLearner 
Merged it.

**Pull request merged**
