### PR TITLE
virt: update autoinstall.xml for sles10

### PR DESCRIPTION
**Pull request by xutian**
clean net udev rules and rename eth configuration to
make guest get ip address from dhcp server by default.

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1139472

**Comment by xutian** [comment]
[root@dhcp-8-209 qemu]# ../../../../../../tools/scan_results.py 
Test                                                                                                                                                                                               Status     Seconds  Info
----                                                                                                                                                                                               ------     -------  ----
        (Result file: /root/staf-kvm-devel/autotest-devel/client/results/default/status)
virt.qemu.smp_2.4096m.repeat1.pre_test.Host_RHEL.7.1.qcow2.virtio_blk.up.virtio_net.SLES.10.4.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native    GOOD       381      completed successfully
virt.qemu.smp_2.4096m.repeat1.run_test.Host_RHEL.7.1.qcow2.virtio_blk.up.virtio_net.SLES.10.4.x86_64.io-github-autotest-qemu.shutdown                                                              GOOD       283      completed successfully
virt.qemu.smp_2.4096m.repeat1.post_check.Host_RHEL.7.1.qcow2.virtio_blk.up.virtio_net.SLES.10.4.x86_64.io-github-autotest-qemu.boot                                                                GOOD       171      completed successfully
----                                                                                                                                                                                               GOOD       848      
[root@dhcp-8-209 qemu]#

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by xutian** [comment]
Thanks   @CongSmile  and @suqinhuang

**Pull request merged**
