### PR TITLE
Provide portal_ip for iscsi setup.

### PR DESCRIPTION
**Pull request by rbian**
Ipv6 portal address can'be created by default, we need to add a parameter
add then create ipv6 portal if needed.

### CODE REVIEW

**Comment by waynesun09** [comment]
ipaddr not python standard library, so travis failed unittest at import it.

**Comment by rbian** [comment]
@waynesun09 , Yes, any suggestion to avoid this?

**Comment by waynesun09** [comment]
@rbian 
since ipaddress is in python 3, so we can't use it also.
then maybe wirte a new function in utils_net using socket

**Comment by waynesun09** [comment]
ACK

**Comment by waynesun09** [comment]
@rbian I'm merging this now, looking forward your fix on lun_num on iscsi, thx

**Pull request merged**
