### PR TITLE
Libvirt: Add memballoon support for vm create

### PR DESCRIPTION
**Pull request by sathnaga**
This adds support for creating VM with memballoon device using virt-install

### CODE REVIEW

**Comment by waynesun09** [comment]
ACK

**Comment by Hao-Liu** [comment]
I recommend substitute `driver` with `model` for consistency with libvirt terminology. Other LGTM.

**Comment by sathnaga** [comment]
@waynesun09 Thanks :-)
@Hao-Liu Thanks, have taken care your recommendation :-)

**Comment by Hao-Liu** [comment]
Thanks @sathnaga @waynesun09. Merged.

**Comment by sathnaga** [comment]
Closing as merged

**Pull request merged**
