### PR TITLE
Add restart tgtd option in iscsi module

### PR DESCRIPTION
**Pull request by waynesun09**
Add the new param in init and update libvirt iscsi config function to support use it.

### CODE REVIEW

**Comment by CongSmile** [comment]
Hi,

On RHEL.7, tgtd service is called targetd.

Could you check it?

Thanks.

**Comment by waynesun09** [comment]
@CongSmile I think you mean "target" service, 'target' and 'tgtd' are two services.

RHEL 7 and upstream is using the LIO kernel target subsystem for iSCSI and other protocols, instead of the tgtd daemon, while tgtd is supported in EPEL on RHEL7.
virt-test did not support LIO now, we still use tgtd as iscsi initiator which with backward compatibility.
LIO support is welcomed and looking forward the progress.

**Comment by CongSmile** [comment]
# service tgtd status
Redirecting to /bin/systemctl status  tgtd.service
tgtd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
# uname -r
3.10.0-234.el7.x86_64
# rpm -qa | grep iscsi
iscsi-initiator-utils-6.2.0.873-29.el7.x86_64
libiscsi-1.9.0-6.el7.x86_64
iscsi-initiator-utils-iscsiuio-6.2.0.873-29.el7.x86_64

I'm not sure whether I have missed some packages or others.
But there is no tgtd service on RHEL.7 on my host, it's strange.

Could you check it?

**Comment by waynesun09** [comment]
@CongSmile you need scsi-target-utils rpm

**Comment by waynesun09** [comment]
@CongSmile you need to install EPEL rhel7 repo rpm, then yum install scsi-target-utils rpm
for EPEL:
https://fedoraproject.org/wiki/EPEL

**Comment by CongSmile** [comment]
@waynesun09 

Oh, yes, thanks for you help, I missed the package.

It looks good to me now.

Acked-by: Cong Li <coli@redhat.com>

**Comment by Hao-Liu** [comment]
ACK and Merging, Thanks @waynesun09 @CongSmile.

**Pull request merged**
