### PR TITLE
virt-test: unattended: disable lock media rules in udev for SLES.12

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

### CODE REVIEW

**Comment by CongSmile** [comment]
id: 1176747

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by xutian** [comment]
LGTM,

Acked-by: Xu Tian <xutian@redhat.com>

**Comment by FengYang** [comment]
Thanks @CongSmile

**Pull request merged**
