### PR TITLE
virttest.qemu_qtree: Remove the quotations in image name

### PR DESCRIPTION
**Pull request by ypu**
Corrently the image name will include two quotations in the string.
And this will failed the parse. So remove the quotations to make
it work as expect.

### CODE REVIEW

**Comment by ypu** [comment]
@xutian think about this again. And decide to update the code. Thanks for your comments. Can you help to review it again?

**Comment by xutian** [comment]
LGTM,

Acked-by: @xutian

**Comment by FengYang** [comment]
Acked-by: FengYang

**Comment by FengYang** [comment]
Thanks @ypu @xutian

**Pull request merged**
