### PR TITLE
virt.qemu_monitor: Do not call utils_misc.log_line() to log the monitor ...

### PR DESCRIPTION
**Pull request by FengYang**
...output

Now we call utils_misc.log_line() to save some logs.
Then script may fail to get log to access _open_log_files, especially when we
want to log many logs.

So handle monitor log in monitor class now.

Signed-off-by: Feng Yang <fyang@redhat.com>

### CODE REVIEW

**Comment by FengYang** [comment]
ID: 1181439

**Comment by ypu** [comment]
Hi @FengYang the patch looks good to me. But can you rebase it to make it pass the travis test?

**Comment by FengYang** [comment]
On 03/11/2015 05:35 PM, Yiqiao Pu wrote:
>
> Hi @FengYang <https://github.com/FengYang> the patch looks good to me.
> But can you rebase it to make it pass the travis test?
>
Seems it is check script issue.  Re-submit the patch. Now it pass.

Thanks

**Comment by ypu** [comment]
@FengYang Hi seems can not find get_log_fie_dir in utils_misc in virt-test. Is there something wrong when you rebase it?

**Comment by FengYang** [comment]
On 03/18/2015 04:29 PM, Yiqiao Pu wrote:
>
> @FengYang <https://github.com/FengYang> Hi seems can not find
> get_log_fie_dir in utils_misc in virt-test. Is there something wrong
> when you rebase it?
>

Hi @ypu, thanks for your comments.

Have add get_log_file_dir() back.

**Comment by FengYang** [comment]
id : 1143797

**Comment by ypu** [comment]
LGTM

Acked-by: Yiqiao Pu <ypu@redhat.com>

**Comment by xutian** [comment]
LGTM,

Acked-by:  Xu Tian <xutian@redhat.com>

**Comment by ypu** [comment]
Thanks @FengYang and @xutian will merge it

**Pull request merged**
