### PR TITLE
virttest.utils_misc: Update format_windows_disk function

### PR DESCRIPTION
**Pull request by spcui**
Add the default value for mountpoint and size parameters.
    
Signed-off-by: Shuping Cui <scui@redhat.com>

### CODE REVIEW

**Comment by spcui** [comment]
ID: 1161065 1123773

**Comment by xutian** [comment]
LGTM,

Acked-by: @xutian

**Comment by luckyh** [comment]
Acked-by: @luckyh

**Comment by FengYang** [comment]
Thanks @spcui, @xutian, @luckyh

**Pull request merged**
