### PR TITLE
vm_xml: get "peak" and "burst" from get_iftune_params()

### PR DESCRIPTION
**Pull request by Chenditang**

### CODE REVIEW

**Comment by will-Do** [comment]
Seems you also change the file mode bits:  ```100644 → 100755```

**Comment by Chenditang** [comment]
@will-Do 

Sorry for my faults, updated.
Thanks~~

**Comment by will-Do** [comment]
ACK

**Comment by lmr** [comment]
Hi @Chenditang. As you might know, we're moving virt-test to avocado-vt, so I please ask you to consider re-implementing this functionality in the later. The new repo is:

https://github.com/avocado-framework/avocado-vt

Please keep in mind the following guidelines when creating the new PR:

1) Most of the time you can pick the patches of your original PR and merge them on a new branch with minimal changes.
3) Don't use autotest APIs, since we're moving away from using them. Please review the code and change things like `utils.system` -> `process.system`, `utils.run` -> `process.run`, so on and so forth.

Thanks, and I'm sorry for any inconveniences we might have caused your team.

**Pull request closed without merging**
