### PR TITLE
virt-test: guest-hw.cfg: specify cd_format for different drive_format.

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

### CODE REVIEW

**Comment by CongSmile** [comment]
id: 1223245

**Comment by xutian** [comment]
Hi @CongSmile 

we still need config to limited windows unattended_install.cdrom test used ide-cd, so that guest can read files from cdrom without extra virtio drive support.

**Comment by CongSmile** [comment]
Hi @xutian 

Thanks for your review at first.

Yes, we have already set installation with cd_format=ide in machines.cfg.
which will cover the guest-hw.cfg.
variants:
    - @i440fx:
        only i386, x86_64
        machine_type = pc
        unattended_install..cdrom, unattended_install..extra_cdrom_ks:
            cd_format = ide

Thanks.

**Comment by xutian** [comment]
@CongSmile 

Ok,  just want to confirm it. LGTM
Acked-by: Xu Tian <xutian@redhat.com>

**Comment by PyLearner** [comment]
Acked-by: Meng Yang meyang@redhat.com

**Comment by ypu** [comment]
Thanks @CongSmile, @PyLearner  and @xutian will merge it.

**Pull request merged**
