### PR TITLE
the QemuImg class doesn't have a params attribute, causing failures at postprocess

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1250913

**Comment by xutian** [comment]
@lmr  updated commit by your comment, would you help to review it.

Thanks,
Xu

**Comment by xutian** [comment]
@lmr 
There so many task need to do in QemuImg class, eg, we need to unify API (eg. backup/remove/restore image) for different image backend (like, ceph, iscsi, nfs and so on). We hope we can reconstruction this class in future. 
And this fix just a hotfix to make our testing task no blocked by this syntax in QemuImg.info.

Thanks,
@xutian

**Comment by xutian** [comment]
@lmr 

For "--backing-chain" option @Chenditang  has a special test case to test it. see below PR https://github.com/autotest/tp-qemu/pull/406

**Comment by lmr** [comment]
Ok, could you please fix the typo and re-submit? Thanks!

**Comment by xutian** [comment]
Sorry for typo and my poor English. Thanks

**Comment by xutian** [comment]
@lmr 
Updated and fixed typo in this PR. thanks

**Comment by lmr** [comment]
Awesome, approved, thanks!

**Pull request merged**
