### PR TITLE
Virtio serial

### PR DESCRIPTION
**Pull request by FengYang**
ID :  1185183

### CODE REVIEW

**Comment by FengYang** [comment]
[root@hp-z800-01 qemu]# ../../../../../../tools/scan_results.py 
Test                                                                                                                            Status     Seconds  Info
----                                                                                                                            ------     -------  ----
        (Result file: /usr/code/autotest/client/results/default/status)
virt.qemu.Host_RHEL.7.0.qcow2.virtio_blk.smp2.virtio_net.RHEL.7.0.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer    GOOD       30       completed successfully
----                                                                                                                            GOOD       33       
[root@hp-z800-01 qemu]#

**Comment by lmr** [comment]
You do need to rebase your PR and re-submit, @FengYang .

**Comment by FengYang** [comment]
On 03/04/2015 09:39 PM, Lucas Meneghel Rodrigues wrote:
>
> You do need to rebase your PR and re-submit, @FengYang
> <https://github.com/FengYang> .
>

OK, will do it.

**Comment by lmr** [comment]
@FengYang, please fix the problems found by Travis and update.

**Comment by FengYang** [comment]
On 03/20/2015 03:16 AM, Lucas Meneghel Rodrigues wrote:
>
> @FengYang <https://github.com/FengYang>, please fix the problems found
> by Travis and update.
>

OK, already update one times, seems still have some left. Will update it
again.

**Comment by FengYang** [comment]
On 03/20/2015 03:16 AM, Lucas Meneghel Rodrigues wrote:
>
> @FengYang <https://github.com/FengYang>, please fix the problems found
> by Travis and update.
>

Hi @lmr

Already fix the error.  Thanks

**Comment by ypu** [comment]
LGTM

Acked-by: Yiqiao Pu <ypu@redhat.com>

**Comment by lmr** [comment]
@FengYang, thanks!

**Pull request merged**
