### PR TITLE
virttest.utils_net: Try default route if selected route could not work.

### PR DESCRIPTION
**Pull request by FengYang**
When host have multi network card in same subnet, guset may fail at
mac ip verify. Because code may ge a wrong device from ip route.

Signed-off-by: Feng Yang <fyang@redhat.com>

### CODE REVIEW

**Comment by FengYang** [comment]
id : 1203515

**Comment by xutian** [comment]
@FengYang 

I think verify_ip_mac_owner_ship inneed in current framework, so I drop it in https://github.com/autotest/virt-test/pull/2091

thanks,
Xu

**Comment by FengYang** [comment]
On 03/23/2015 04:52 PM, Xu Tian wrote:
>
> @FengYang <https://github.com/FengYang>
>
> I think verify_ip_mac_owner_ship inneed in current framework, so I
> drop it in #2091 <https://github.com/autotest/virt-test/pull/2091>
>
> thanks,
> Xu
>

I think we still need it.  Or sometimes we do not know why could not
login.  Or we may try to login a old ip which already used by another
VM, It may effect other case.  So verify the ip and mac before using it
is always a good idea. That is also why we add them before.

We just need disable it for some devices, e.g macvtap and sr-iov.

**Comment by xutian** [comment]
On 03/23/2015 05:23 PM, Feng Yang wrote:
>
>
> On 03/23/2015 04:52 PM, Xu Tian wrote:
> >
> > @FengYang <https://github.com/FengYang>
> >
> > I think verify_ip_mac_owner_ship inneed in current framework, so I
> > drop it in #2091 <https://github.com/autotest/virt-test/pull/2091>
> >
> > thanks,
> > Xu
> >
>
> I think we still need it. Or sometimes we do not know why could not
> login. Or we may try to login a old ip which already used by another
> VM, It may effect other case. So verify the ip and mac before using it
> is always a good idea. That is also why we add them before.
>
> We just need disable it for some devices, e.g macvtap and sr-iov.
I think we use expired IP address because  we record IP address in 
virtnet's db, But Now we have reset in it virtnet code.

**Comment by xutian** [comment]
LGTM,

Acked-by: Xu Tian <xutian@redhat.com>

**Comment by ypu** [comment]
LGTM

Acked-by: Yiqiao Pu <ypu@redhat.com>

Thanks @FengYang and @xutian will merge it.

**Pull request merged**
