### PR TITLE
virttest.qemu_devices: Update for spapr-vscsi device

### PR DESCRIPTION
**Pull request by ypu**
As spapr-vscsi is not a pci device, it should not be added to pci bus.
Also add the option bus for spapr-vscsi device as the default bus for
scsi-hd is virtio_scsi bus.

### CODE REVIEW

**Comment by ypu** [comment]
ID: 1220355

**Comment by luckyh** [comment]
Acked

**Comment by Zhengtong** [comment]
Acked

**Comment by ngu-niny** [comment]
Acked.
On ppc64le host, after download the upstream autotest/virt-test/tp-qemu code and 'git am' the patch, I have run some basic function test cases, i.e. unattended install, boot, reboot, system_powerdown, the test is passed without any the patch related problem. The software versions on the host/guest are:
Host kernel: 3.10.0-244.ael7b.ppc64le
Guest kernel: 3.10.0-229.el7.ppc64/3.10.0-229.ael7b.ppc64le
Qemu KVM: qemu-kvm-rhev-2.3.0-1.ael7b.ppc64le

**Comment by ypu** [comment]
Thanks @luckyh @Zhengtong & @ngu-niny will merge it.

**Pull request merged**
