### PR TITLE
Add te detail information of PING command to improve the debug log

### PR DESCRIPTION
**Pull request by yaxue**
Signed-off-by: Yang Xue <yaxue@redhat.com>

### CODE REVIEW

**Comment by FengYang** [comment]
Thanks @yumingfei and @yaxue. Will merge this patch to FengYang@d6b35d9

**Comment by FengYang** [comment]
Check again. We did not update same function. Will not effect each other. So we can directly merge this once.

**Comment by FengYang** [comment]
Acked-by: Feng Yang fyang@redhat.com

**Comment by yumingfei** [comment]
OK

**Pull request merged**
