### PR TITLE
virttest: Update check_guests_proc_scsi in qemu_qtree

### PR DESCRIPTION
**Pull request by ypu**
Current output of qtree will include hex numbers and this makes
the transfer from string to int failed. So remove it to make the function
works as expect.

### CODE REVIEW

**Comment by ypu** [comment]
ID: 1104911

**Comment by spcui** [comment]
LGTM
Acked-by: @spcui

**Comment by xutian** [comment]
LGTM,

Acked-by: @xutian

**Comment by ypu** [comment]
Thanks @spcui and @xutian will merge it.

**Pull request merged**
