### PR TITLE
virt-test.shared.scripts: Add some scripts for openflow acl test

### PR DESCRIPTION
**Pull request by ypu**
These two scripts are used in openflow control test in windows guest.

### CODE REVIEW

**Comment by ypu** [comment]
ID: 1197624

**Comment by spcui** [comment]
LTGM
Acked-by: @spcui

**Comment by spcui** [comment]
LTGM
Acked-by: @spcui

**Comment by xutian** [comment]
LGTM,

Acked-by: @xutian

**Comment by ypu** [comment]
Thanks @spcui and @xutian will merge it.

**Pull request merged**
