### PR TITLE
virt-test: add check before add virtocosole device

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1228538

**Comment by xutian** [comment]
@spcui , no need to do it,  we will keep internal code to run with  python <= python2.4 and old qemu version.

**Comment by xutian** [comment]
@CongSmile  and @spcui 

Any comment on this change?

**Comment by spcui** [comment]
OK, LGTM
Acked-by: scui@redhat.com

**Pull request merged**
