### PR TITLE
Add iscsi nfs image backend and  display varinat support

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
@swapnakrishnan2k @waynesun09 

I add display variants in guest-hw.cfg, and we use vnc as default qemu display.  Would you like to looks at it that if it will impact your tests. 

Thanks,
Xu

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by xutian** [comment]
Merged. thanks @CongSmile  and @suqinhuang

**Comment by xutian** [comment]
ID: 1244619

**Pull request merged**
