### PR TITLE
Cleanup get IP address  releated function

### PR DESCRIPTION
**Pull request by xutian**
After fef5c4c5cd2da1b7509283f3b3db06166c4c8615 applied, not we need cleanup code for implement ip_pool.

thanks,
Xu

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1205052

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by spcui** [comment]
LGTM
Acked-by: @spcui

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by ypu** [comment]
Hi @xutian seems there is something wrong that you didn't init ip_pool in address_cache at first time.
If I remove the env and address_pool files it will report following error:

    File "/root/autotest-devel/client/tests/virt/virttest/virt_vm.py", line 922, in login
      address = self.get_address(nic_index)
    File "/root/autotest-devel/client/tests/virt/virttest/virt_vm.py", line 689, in get_address
      self.address_cache["ip_pool"].discard(arp_ip)
  KeyError: 'ip_pool'

**Comment by xutian** [comment]
@ypu  thanks for your test. And PR has update, would you help to review it.

Thanks,
Xu

**Comment by ngu-niny** [comment]
On ppc64le host for the test on RHEL6.7, before applied the patch, it could not get the ip of the guest with following error:

[root@ibm-p8-kvm-01-qe default-0707-acceptance1]# cat virt.qemu.repeat1.spapr_vscsi_test.qcow2.spapr_vscsi.up.spapr-vlan.RHEL.6.7.ppc64.io-github-autotest-qemu.format_disk/debug/virt.qemu.repeat1.spapr_vscsi_test.qcow2.spapr_vscsi.up.spapr-vlan.RHEL.6.7.ppc64.io-github-autotest-qemu.format_disk.ERROR 
07/07 04:49:58 ERROR|      virt:0171| Test failed: LoginTimeoutError: Login timeout expired    (output: '')
07/07 04:50:59 ERROR|      test:0414| Exception escaping from test:
Traceback (most recent call last):
  File "/media/ngu/autotest-devel/client/shared/test.py", line 411, in _exec
    _call_test_function(self.execute, *p_args, **p_dargs)
  File "/media/ngu/autotest-devel/client/shared/test.py", line 830, in _call_test_function
    raise error.UnhandledTestFail(e)
UnhandledTestFail: Unhandled LoginTimeoutError: Login timeout expired    (output: '')    [context: Login to the guest --> logging into 'virt-tests-vm1' via serial_console]
Traceback (most recent call last):
  File "/media/ngu/autotest-devel/client/shared/test.py", line 823, in _call_test_function
    return func(*args, **dargs)
  File "/media/ngu/autotest-devel/client/shared/test.py", line 291, in execute
    postprocess_profiled_run, args, dargs)
  File "/media/ngu/autotest-devel/client/shared/test.py", line 209, in _call_run_once
    *args, **dargs)
  File "/media/ngu/autotest-devel/client/shared/test.py", line 313, in run_once_profiling
    self.run_once(*args, **dargs)
  File "/media/ngu/autotest-devel/client/tests/virt/virt.py", line 155, in run_once
    run_func(self, params, env)
  File "/media/ngu/autotest-devel/client/shared/error.py", line 141, in new_fn
    return fn(*args, **kwargs)
  File "/media/ngu/autotest-devel/client/tests/virt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/format_disk.py", line 29, in run
    session = vm.wait_for_login(timeout=int(params.get("login_timeout", 360)))
  File "/media/ngu/autotest-devel/client/tests/virt/virttest/virt_vm.py", line 1025, in wait_for_login
    password=password)
  File "/media/ngu/autotest-devel/client/tests/virt/virttest/virt_vm.py", line 1220, in wait_for_serial_login
    password, virtio=virtio)
  File "/media/ngu/autotest-devel/client/shared/error.py", line 141, in new_fn
    return fn(*args, **kwargs)
  File "/media/ngu/autotest-devel/client/tests/virt/virttest/virt_vm.py", line 1179, in serial_login
    remote.handle_prompts(console, username, password, prompt, timeout)
  File "/media/ngu/autotest-devel/client/tests/virt/virttest/remote.py", line 192, in handle_prompts
    raise LoginTimeoutError(e.output)
LoginTimeoutError: Login timeout expired    (output: '')
[root@ibm-p8-kvm-01-qe default-0707-acceptance1]# 

While after applied the patch, the guest ip could be obtained without any error.

**Comment by xutian** [comment]
thanks @ypu  @CongSmile  @spcui  and @ngu-niny. Merged.

**Pull request merged**
