### PR TITLE
virttest.utils_spice: Add support for RHEL7

### PR DESCRIPTION
**Pull request by swapnakrishnan2k**
For spice tests on RHEL7, adding EPEL support for RHEL7
and restarting gdm in RHEL7 is required. 

Reviewed By: Swapna Krishnan <skrishna@redhat.com>

### CODE REVIEW

**Comment by ypu** [comment]
LGTM

Acked-by: Yiqiao Pu <ypu@redhat.com>

**Comment by FengYang** [comment]
@swapnakrishnan2k 

Code looks good for me. But it seems fail for style check.

Could you make a little update for the code style.  Then we can apply it.
Thanks

**Comment by swapnakrishnan2k** [comment]
I added the PEP8 fix too. Do you need me to merge the commits together?

**Comment by FengYang** [comment]
It is fine for me.

Will merge it.

Thanks @swapnakrishnan2k  and @ypu

**Pull request merged**
