### PR TITLE
shared.cfg.guest-os: Add RHEL.7.1 guest config

### PR DESCRIPTION
**Pull request by spcui**
1. Add RHEL.7.1 guest config
2. Small update for RHEL.7.0 config

Signed-off-by: Shuping Cui <scui@redhat.com>

### CODE REVIEW

**Comment by spcui** [comment]
ID: 1200243

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by FengYang** [comment]
Looks good to me.

Acked-by: Feng Yang

**Comment by FengYang** [comment]
Thanks @spcui and @CongSmile , Will merge it.

**Pull request merged**
