### PR TITLE
virttest/qemu_vm: fix pep8 E126

### PR DESCRIPTION
**Pull request by PandaWei**
E126 means continuation line over-indented for hanging indent.

### CODE REVIEW

**Comment by Hao-Liu** [comment]
ACK and Merging. But still wondering why my pep8 and pylint turn a blind eye to this.

**Comment by PandaWei** [comment]
Labor Day coming, Maybe your pep8 and pylint also want to have a rest and have good holiday...
Just a joke.. ^_^

**Comment by PandaWei** [comment]
Thanks for your help and comment on my PR.

**Comment by Hao-Liu** [comment]
I just want to take the vacation with my pep8 and pylint without any concerns about he overflowing pull requests.
Please forgive my lousy joke. It's just pleasure to review your code. Nice job.

**Pull request merged**
