### PR TITLE
virttest.libvirt_xml.devices: update sound XML

### PR DESCRIPTION
**Pull request by chuanchang**
Signed-off-by: Alex Jia <ajia@redhat.com>

### CODE REVIEW

**Comment by waynesun09** [comment]
@chuanchang the pylint problem solved by @Hao-Liu , pls rebase to avoid travis failure. Thanks.

**Comment by chuanchang** [comment]
@waynesun09, okay, I just rebased codes, thanks a lot!

**Comment by will-Do** [comment]
ack

**Comment by waynesun09** [comment]
ACK, merging now.
@will-Do @chuanchang thx

**Pull request merged**
